version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    network_mode: host
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: person-db

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    network_mode: host

  prometheus:
    image: prom/prometheus
    restart: always
    user: root
    ports:
      - 9090:9090
    network_mode: host
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

volumes:
  prometheus-data: