version: "3"
networks:
  demo-network:
    driver: bridge
services:
  postgres:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo
    networks:
      - demo-network
    volumes:
      - /media/postgres:/var/lib/postgresql
    ports:
      - 5432:5432
